baseurl = "/"
disqusShortname = "sierrasoftworks"
googleAnalytics = "UA-40095482-1"
languageCode = "en-GB"
paginate = 20
pygmentsCodeFences = true
pygmentsUseClasses = true
sectionPagesMenu = "menu"
theme = "minimalist"
themesDir = "themes"
title = "Sierra Softworks"
[[menu.main]]
name = "Archived Projects"
title = "View some of the previous projects I've worked on"
weight = 2
[[menu.main]]
name = "GitHub"
pre = "<i class='icon-github'></i>"
title = "View my open source GitHub projects"
url = "https://github.com/SierraSoftworks"
weight = 5
[params]
avatar = "https://cv.sierrasoftworks.com/resources/avatar.jpg"
copyright = "Copyright Sierra Softworks"
custom_css = ["/css/custom.css"]
custom_js = ["https://js.sentry-cdn.com/9b2237ebb25e438bb6bf3b819c419495.min.js"]
google_analytics = "UA-40095482-1"
location = "Dublin, Ireland"
logo = "https://cdn.sierrasoftworks.com/logos/icon.png"
occupation = "Site Reliability Engineer, Microsoft"
site_author = "Benjamin Pannell"
site_description = "The official Sierra Softworks blog"
subtitle = "Blog"
[permalinks]
post = "/:year/:month/:day/:filename/"
[social]
behance = ""
dribbble = ""
facebook = ""
github = "SierraSoftworks"
gplus = ""
instagram = "notheotherben"
linkedin = ""
twitter = "SierraSoftworks"
